### ISSUE TITLE
Are you just removing everything with the word server or virtual in it?

### ISSUE THREAD

**Issue by bongochong** [butteff/Ubuntu-Telemetry-Free-Privacy-Secure#1]
Hey anon, Lines 66 through 85 (the entire "other" section) will break people's ubuntu desktops in bad, bad ways. Please delete them before anyone else gets hurt.

Line 50  (denying outgoing connections) should be deleted, as it will screw up accessing shit via ftp, bittorrent, and other protocols.

The lines regarding zeitgeist will break some basic functionality in ubuntu, so they should be deleted as well.

If you're going to leave this script up on github, you should really remove these lines... unless you did this as a joke. It's not funny to me, but who am I to judge how you get your giggles?

**Comment by butteff** [comment]
> will break people's ubuntu desktops

But it will not. I use the script in my 16.10 ubuntu

>(denying outgoing connections) should be deleted, as it will screw up accessing shit via ftp, bittorrent, and other protocols.

But if user will need it, he should to add the rule manually. I can't to know what user will use, what not.

>The lines regarding zeitgeist will break some basic functionality in ubuntu

Zeitgeist is basic Telemetry stuff, and the main idea of the script - to remove any telemetry in ubuntu (of course, the script will not save from all dangers, like telemetry in kernel, but anyway it is better to have without it)

Anyway, I've wrote about, that script should to be readed first, in Readme file.

**Comment by bongochong** [comment]
gvfs-fuse is necessary for mounting a number of different file systems, so removing it is breaking a core feature of the desktop. snapd is Ubuntu's new flatpak equivalent and is necessary for kernel livepatching, so removing it will break a great new feature that many people, especially sysadmins would want to use. The xserver-xorg package is useful for VirtualBox, a product for running virtual machines that is used by millions of people. The unity-scope-video packages allow the unity video scope to function, so removing them breaks a standard feature of the desktop. The unity8, libmir, and gdb packages are not security risks in any way and necessary for unity8, which is also not a security risk. The evolution packages and the libfolks package are parts of the GNOME stack, which unity 7 is largely built upon, and they also pose no threat. This is just the tip of the iceberg, and you clearly have no idea why you're removing those packages, except for the fact that you're unfamiliar with them and confused. No one should be using this script. It's absolutely terrible.

**Comment by bongochong** [comment]
And zeitgeist is not telemetry, at all. You have no idea what you're talking about and could mislead other idiots to screw up their installations too.
