### ISSUE TITLE
Link to Subgraph OS

### ISSUE THREAD

**Issue by burdges** [butteff/Ubuntu-Telemetry-Free-Privacy-Secure#3]
If this script is only meant for headless servers then it should say so.  If it's meant for user facing system, then..

I'd think folks who want to improve security of their Ubuntu install should really look into [Subgraph OS](https://subgraph.com/sgos/).  Subgraph is based directly on Debian, not Ubuntu, but Ubuntu is ditching Unity for GNOME 3 anyway, so that only impacts non-free package availability.  

Subgraph is more hardened necessary for some users, but they are great about resolving the pain points.  In particular, Subgraph will [soon](https://github.com/subgraph/subgraph-os-issues/issues/192#issuecomment-294072883) restore support for UEFI, and [started adding](https://github.com/subgraph/subgraph-os-issues/issues/120#issuecomment-274303782) support for internet access not routed over Tor.

**Comment by butteff** [comment]
This github repo is not for anonymous OS using, it just removes some pre-installed unsecure apps and telemetry in ubuntu. In Ubuntu only, not in other OS. And, of course, the script doesn't clean up all of the problems, because I don't know about all, but it anyway gives a little protection.

The main idea is to have more protection, than basic installation and have possibility for disable any private data leak.

**Comment by burdges** [comment]
I appreciate that it's useful to explain that "Ubuntu installs these things by default but you should remove them to make you experience better and more secure", and making it easy to remove them is even more useful, but..

Those in the security community feel the word "secure" comes with an obligation to be honest about the level of security you are actually providing.  You are being honest that all your script does is remove things, but your usage of the word secure may suggest to readers that this suffices for "security".  It does not.  

As I said, Subgraph is increasingly not dependent upon Tor.  As a practical matter, any secure OS must start out being dependent upon Tor because otherwise you'll never even discover if you've adequately controlled network access by applications.  If it's not "anonymity ready" then it's not secure in any sense. 

The solution is to add some text that say _"This script removes several obviously insecure features of Ubuntu. Please do not imagine it secures your machine against serious adversaries however.  If you need real security, then consider using Subgraph OS or Qubes OS instead."_

**Comment by butteff** [comment]
Thank you, will add it to readme
