### ISSUE TITLE
You don't know what you're doing. Please stop pretending. Your script is potentially dangerous.

### ISSUE THREAD

**Issue by bongochong** [butteff/Ubuntu-Telemetry-Free-Privacy-Secure#4]
Hey anon, lines 66 through 85 (the entire "other" section) will break people's desktops in bad, bad ways. Please delete them before anyone else gets hurt. Line 50 (denying outgoing connections) should be deleted, as it will screw up accessing shit via ftp, bittorrent, and other protocols (something most users would not want). The lines regarding zeitgeist will break some basic functionality in Ubuntu, so they should be deleted as well. Zeitgeist is in no way a "telemetry" framework.

gvfs-fuse is necessary for mounting a number of different file systems, so removing it is breaking a core feature of the desktop as well. snapd is Ubuntu's new flatpak equivalent and is necessary for kernel livepatching, so removing it will break a great new feature that many people, especially sysadmins, would want to use. The xserver-xorg package is useful for VirtualBox, a product for running virtual machines that is used by millions of people. The unity-scope-video packages allow the unity video scope to function, so removing them breaks a standard feature of the desktop. The unity8, libmir, and gdb packages are not security risks in any way and necessary for unity8, which is also not a security risk. The evolution packages and the libfolks package are parts of the GNOME stack (a big part of Ubuntu) for messaging, calendar, pim apps, and more. They also pose no threat (while offering useful functionality for communications apps and the like).

This is just the tip of the iceberg, and you clearly have no idea why you're removing those packages, except for the fact that you're unfamiliar with them and confused. No one should be using this script.

**Comment by butteff** [comment]
If someone will need to use, for example, virtualbox, packages will be installed again with main virtualbox package.

If someone will need, for example, FTP - he will add manually rules to ufw.  

Zeitgeist is telemetry database, snapd mark packages too. All this info in google.

Unity8 is not used right now, it is a prreview version and can to have problems, if you don't use it - better to remove it, because can be 0day vulnerabilities, which are not in public.

The script doesn't broke a system, It just clean up it.

**Comment by bongochong** [comment]
Literally any software can have 0day vulnerabilities. If that's the logic you're using, might as well not use a computer at all. Your script does break a normal user's system, and I wonder if you are actually using any kind of Lignux as your main OS, if at all.

**Comment by psvnlsaikumar** [comment]
well, I should have probably read the closed issues before running the script. looks like most of the apps on my machine (even after running a timeshift) are unusable now. before timeshift, my pc would never connect to the internet. idk what else went haywire. thanks to this, I might need to do a fresh install.

**Comment by bongochong** [comment]
No problem. I kind of blurted out my response back then, so the info is a bit disorganized, but in general the comment is on point. You can probably revert the changes by booting into the CLI only and manually undoing the modifications the script made.
